add java8 language support for android
this avoids an ugly "NoSuchMethodError" for a missing metafactory when running the test on an android phone https://stackoverflow.com/questions/59448845/no-static-method-metafactory/59448917#59448917"

Signed-off-by: l-1squared <30831153+l-1squared@users.noreply.github.com>